* ReSync
:PROPERTIES:
:ID:       61ab545c-74f6-4054-90a2-c6d9001c5b5d
:END:

ReSync (REpository SYNChronizer) is a small utility used to continuously and
unilaterally synchronize a master machine (typically a coding machine) with
slaves machines (build or execution machines) in real time.

The name come from the original usage (synchronize a git repository from a
coding machine to a build/execution machine) and is a word play with =rsync=.

* Installation

Install the requirements for Debian-based system:

#+begin_src bash :eval never
sudo apt-get install rsync inotify-tools
#+end_src

Install the requirements for Arch Linux system:

#+begin_src bash :eval never
sudo pacman -S rsync inotify-tools
#+end_src

Configure the system by increasing the inotify's watches for a user, otherwise,
the =Couldn't initialize inotify: Too many open files= error could happened:

#+begin_src bash :results output silent
sudo make configure
#+end_src

Install it in normal mode:

#+begin_src bash :results output silent
sudo make install
#+end_src

Install it in development mode:

#+begin_src bash :results output silent
sudo make install-dev
#+end_src

Uninstall it:

#+begin_src bash :results output silent
sudo make uninstall
#+end_src

* Usage

Call the script with:
1. The repository path as first argument,
2. The machines' SSH names as second (and more) argument(s).

#+begin_src bash :results output silent :var pwd="/home/pierre/work/info/research/projects/screaming_channels/screaming_channels_utils" :var hostname="reaper"
resync $pwd $hostname
#+end_src

The repository will be continuously synchronized to the SSH machine, in a =git=
folder under its home directory (=$REMOTE:$HOME/git=), using =inotify= as
change detection system and =rsync= as transfer system.

* Contributing

Regarding the current installation method, =resync.sh= has to remain a
single-file project for now.

* Tasks

** TODO Improve reliability

Use a system-wide lock file (/e.g./ =touch /tmp/resync-$(pwd)= or using a
symlink) during all =resync= process to not allow launching 2 =resync=
processes in the same git project.

** TODO Improve features

Use a repository-wide lock file (/e.g./ =touch .git/.resync-lock=) during
=rsync= process to allows launching =resync= on two machines for the same repo,
allowing to do duplex synchronization.
